[package]
name = "rugdns"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
hickory-server = { version = "0.25"}
hickory-proto = { version = "0.25", features = ["tls-aws-lc-rs", "https-aws-lc-rs", "webpki-roots"] }
hickory-client = { version = "0.25", features = ["dnssec-aws-lc-rs"] }
rustls = "0.23"
async-trait = { version = "0.1" }
tokio = { version = "1.21", features = ["net", "fs", "process"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
base64 = "0.22"
regex = "1"
data-encoding = "2"
toml = "0.8"
minisign-verify = "0.2"
reqwest = "0.12"
anyhow = "1.0"
serde = "1.0"
