
#  ██████╗ ██╗   ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗
#  ██╔══██╗██║   ██║██╔════╝ ██╔══██╗████╗  ██║██╔════╝
#  ██████╔╝██║   ██║██║  ███╗██║  ██║██╔██╗ ██║███████╗
#  ██╔══██╗██║   ██║██║   ██║██║  ██║██║╚██╗██║╚════██║
#  ██║  ██║╚██████╔╝╚██████╔╝██████╔╝██║ ╚████║███████║
#  ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝

###############################################################################
#                             Global settings                                 #
###############################################################################
bind = "127.0.0.1"
port = 8553
# [0, 256) seconds, 0 means no limit(some task actually will be set to 60s).
timeout_s = 5         
# Number of parallel resolutions per stage, applied separately to non-DNSSEC
# and DNSSEC servers. For example, 3 allows up to 3 parallel queries for each group.
para_num = 3

# Resovler Server Names
# ****************************************************************
# ** The server name is totally compatiable with dnscrypt.info. **
# ** You can choose a server name from the online list:         **
# ** https://dnscrypt.info/public-servers/                      **
# ** Learn more about the lists, see [sources] below.           **
# ** Currently support DoH, DNSCrypt and Plain TCP/UDP only.    **
# ****************************************************************

# Looking for a suitable DNS Server? Use the Interactive map of public
# DNSCrypt and DoH servers worldwide:
# https://dnscrypt.info/map

# The default config works well during the development process in China. :)

#                DoH           DoH       DoH       DoH
proxy_servers = ['alidns-doh', 'google', 'yandex', 'cloudflare']

direct_servers = [
    "alidns-doh"
]

# Use plain TCP/UDP protocol. DNSSEC is disabled unless you define a custom
# These servers are used to parse the domain of proxy_servers, direct_servers
# and queries.
# DNS Stamp below. (eg. google-plain)
# Only `default_servers` accepts plain IP addresses such as '8.8.8.8'.
default_servers = ['223.5.5.5', '8.8.8.8', 'google-plain']

# Acquire dnscript public resolver list from network.
# If all URLs are unreachable, use the offline `resolvers.md` file
[sources]
minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
public_resolvers = [
    "https://download.dnscrypt.info/dnscrypt-resolvers/v3/public-resolvers.md",
    "https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/refs/heads/master/v3/public-resolvers.md",
    "https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/public-resolvers.md",
]

# Define your custom dns servers
# A useful tool: https://dnscrypt.info/stamps
[sources.servers]

google-plain = [
    "sdns://AAEAAAAAAAAABzguOC44Ljg"
]
